import mpmath as mp
from pathlib import Path

mp.mp.dps = 50

output_path = (
    Path(__file__).resolve().parent / "../src/generated/sin_quarter_luts.inc"
)

output_path = output_path.resolve()


def generate_lut(intervals: int) -> str:
    if intervals <= 0:
        raise ValueError("intervals value out of range")

    x = mp.linspace(0, mp.pi / 2, intervals + 1)
    y = [mp.sin(i) for i in x]

    lut = (
    f"""constexpr long double sin_quarter_lut_{intervals}[] = {{ \n"""
        )

    for value in y:
        lut += f"{mp.nstr(value, 21)}L,\n"

    lut += "}; \n\n"

    return lut


header_guard = (
"""
// Generated by tools/generate_luts.py
// Do not edit manually

#pragma once


""")

with open(output_path, "w") as file:
    file.write(f"{header_guard}")

    for idx in (8, 16, 32, 64):
        file.write(generate_lut(idx))
        print(f"written lut_{idx} to file")
